name: release
on:
  push:
    tags:
      - "V*.*.*"

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Build
        run: ./build.sh
      - name: deploy file
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: 59.110.64.232
          port: 22
          username: root
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          scp_source: ac_pack*.tar.gz
          scp_target: /root/active_center/
