name: release
on:
  push:
    tags:
      - "V*.*.*"

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Build
        run: ./build.sh
      - name: deploy file
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: 59.110.64.232
          port: 22
          username: root
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          scp_source: ac_pack*.tar.gz
          scp_target: /root/active_center/
      - name: start_server
        uses: D3rHase/ssh-command-action@{version}
        with:
          HOST: 59.110.64.232                            # Remote server address / ip - Required: true
          PORT: 22                          # Remote server port -  Default: 22 - Required: false
          USER: root                             # Remote server user - Required: true
          PRIVATE_SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}       # Private ssh key registered on the remote server - Required: true
          COMMAND: pushd /root/active_center; tar xf ac_pack_$(date +%Y%m%d).tar.gz && ./deploy.sh;popd 
